program: spd/scripts/tms_decomposition.py
method: grid
metric:
  name: final_closeness
  goal: minimize
parameters:
  batch_size:
    values: [512, 2048, 8192]
  lr:
    values: [1e-1, 1e-2, 1e-3, 1e-4]
  pnorm:
    values: [0.1, 0.3, 0.5, 0.7]
  max_sparsity_coefficient:
    values: [1e-2, 1e-3, 1e-4]
command:
- ${env}
- ${interpreter}
- ${program}
- spd/scripts/tms_config.yaml