wandb_project: spd-tms
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
n_features: 5
n_hidden: 2
n_instances: 6
batch_size: 8192
steps: 40_000
print_freq: 4000
lr: 1e-2
max_sparsity_coeff: 5e-4
pnorm: 0.5
pnorm_end: null
lr_scale: constant
lr_warmup_pct: 0.1
sparsity_loss_type: jacobian
sparsity_warmup_pct: 0.0
bias_val: 0.0
train_bias: true
feature_probability: 0.05
