wandb_project: spd-tms
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
n_features: 5
n_hidden: 2
n_instances: 12
batch_size: 2048
steps: 100_000
print_freq: 5000
lr: 8e-4
max_sparsity_coeff: 5e-3
pnorm: 0.9
pnorm_end: null
lr_scale: constant
lr_warmup_pct: 0.1
sparsity_loss_type: jacobian
sparsity_warmup_pct: 0.0
bias_val: 0.0
train_bias: true
feature_probability: 0.05
pretrained_model_path: null