program: spd/scripts/tms/tms_decomposition.py
method: grid
metric:
  name: final_closeness
  goal: minimize
parameters:
  lr:
    values: [5e-3, 1e-3]
  pnorm:
    values: [0.7]
  max_sparsity_coeff:
    values: [3, 8, 12]
command:
- ${env}
- ${interpreter}
- ${program}
# - spd/scripts/tms/tms_config.yaml
- spd/scripts/tms/tms_match_param_config.yaml