wandb_project: spd-piecewise
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
topk: 3
max_sparsity_coeff: 0.2
batch_size: 256
steps: 20_000
print_freq: 1000
save_freq: 10_000
lr: 1e-2
lr_scale: constant
lr_warmup_pct: 0.1
loss_type: param_match
torch_model_config:
  torch_model_type: piecewise
  n_functions: 7
  k: 3