wandb_project: spd-linear
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
batch_size: 128
steps: 100_000
print_freq: 2000
save_freq: 10_000
lr: 1e-2
max_sparsity_coeff: 1.5
pnorm: 0.9
pnorm_end: null
lr_scale: constant
lr_warmup_pct: 0.1
sparsity_loss_type: jacobian
sparsity_warmup_pct: 0.0
pretrained_model_path: spd/scripts/linear/out/linear.pt